import datetime as dt
import streamlit as st
import pandas as pd

# Set page config
st.set_page_config(page_title="ecommerce-analytics-dashboard", layout="wide")

# Title
st.title("ecommerce-analytics-dashboard")

# Initialize session configured for generated Streamlit apps
session = st.connection("snowflake").session()
try:
  session.query_tag = "__generated_streamlit"
except Exception:
  pass

@st.cache_data(ttl="23h50m")
def execute_query(query: str) -> str:
  return session.sql(query).collect_nowait().query_id

def query_1_1() -> str:
  sql_query = r"""
select * from mart_daily_sales_by_region;  """

  return sql_query

execute_query(query_1_1())

@st.fragment
def cell_1_1():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      with st.container(height=80, border=False, vertical_alignment="center"):
        st.markdown("### Daily Sales")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_1_1", help="Refresh daily_sales data"
      ):
        execute_query.clear(query_1_1())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_1_1())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for line chart with aggregation
      if len(df) > 0:
        df = df.groupby(
          by="ORDER_DATE",
          sort=False
        ).agg(
          col1=("TOTAL_SALES", "sum")
        ).rename(columns={
          "col1": "TOTAL_SALES (sum)"
        }).reset_index()

        st.area_chart(
          df.set_index("ORDER_DATE"),
          width="stretch",
          height=400,
          x_label="ORDER_DATE",
          y_label="TOTAL_SALES"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

def query_1_2() -> str:
  sql_query = r"""
select * from mart_top_10_customers;  """

  return sql_query

execute_query(query_1_2())

@st.fragment
def cell_1_2():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      with st.container(height=80, border=False, vertical_alignment="center"):
        st.markdown("### Top 10 Customers by Total Spend")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_1_2", help="Refresh top_10_customers_by_total_spend data"
      ):
        execute_query.clear(query_1_2())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_1_2())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for bar chart
      if len(df) > 0:
        df = df.groupby(
          by="CUSTOMER_ID",
          sort=False
        ).agg(
          col1=("TOTAL_SPEND", "sum")
        ).rename(columns={
          "col1": "TOTAL_SPEND (sum)"
        }).reset_index()

        df["/* Order Key (Generated by Snowflake) */"] = df.drop(columns="CUSTOMER_ID").sum(axis=1)

        datetime_primary_column = None
        if pd.api.types.is_datetime64_dtype(df["CUSTOMER_ID"]):
          datetime_primary_column = df["CUSTOMER_ID"]
        elif df["CUSTOMER_ID"].dtype == "object" and isinstance(df["CUSTOMER_ID"].get(df["CUSTOMER_ID"].first_valid_index()), dt.date):
          datetime_primary_column = pd.to_datetime(df["CUSTOMER_ID"], errors="coerce")
        if datetime_primary_column is not None and (datetime_primary_column.max() - datetime_primary_column.min()).days > len(df) * 2:
          # Use string type for sparse date range
          df["CUSTOMER_ID"] = df["CUSTOMER_ID"].astype("string")

        st.bar_chart(
          df,
          x="CUSTOMER_ID",
          y=[c for c in df.columns if c != "CUSTOMER_ID" and c != "/* Order Key (Generated by Snowflake) */"],
          sort="-/* Order Key (Generated by Snowflake) */",
          width="stretch",
          height=400,
          horizontal=True,
          stack=False,
          x_label="TOTAL_SPEND",
          y_label="CUSTOMER_ID"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

# Row 1: 2 Cells
col1_1, col1_2 = st.columns(2)
with col1_1:
  cell_1_1()
with col1_2:
  cell_1_2()

def query_2_1() -> str:
  sql_query = r"""
select * from mart_product_performance;  """

  return sql_query

execute_query(query_2_1())

@st.fragment
def cell_2_1():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      with st.container(height=80, border=False, vertical_alignment="center"):
        st.markdown("### Product Performace")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_2_1", help="Refresh product_performace data"
      ):
        execute_query.clear(query_2_1())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_2_1())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for bar chart
      if len(df) > 0:
        df = df.groupby(
          by="PRODUCT_NAME",
          sort=False
        ).agg(
          col1=("REVENUE", "sum")
        ).rename(columns={
          "col1": "REVENUE (sum)"
        }).reset_index()

        df["/* Order Key (Generated by Snowflake) */"] = df.drop(columns="PRODUCT_NAME").sum(axis=1)

        datetime_primary_column = None
        if pd.api.types.is_datetime64_dtype(df["PRODUCT_NAME"]):
          datetime_primary_column = df["PRODUCT_NAME"]
        elif df["PRODUCT_NAME"].dtype == "object" and isinstance(df["PRODUCT_NAME"].get(df["PRODUCT_NAME"].first_valid_index()), dt.date):
          datetime_primary_column = pd.to_datetime(df["PRODUCT_NAME"], errors="coerce")
        if datetime_primary_column is not None and (datetime_primary_column.max() - datetime_primary_column.min()).days > len(df) * 2:
          # Use string type for sparse date range
          df["PRODUCT_NAME"] = df["PRODUCT_NAME"].astype("string")

        st.bar_chart(
          df,
          x="PRODUCT_NAME",
          y=[c for c in df.columns if c != "PRODUCT_NAME" and c != "/* Order Key (Generated by Snowflake) */"],
          sort="-/* Order Key (Generated by Snowflake) */",
          width="stretch",
          height=400,
          horizontal=True,
          stack=False,
          x_label="TOTAL_REVENUE",
          y_label="PRODUCT_NAME"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

def query_2_2() -> str:
  sql_query = r"""
select sum(case when churn_status='churned' then 1 else 0 end)*1.0/count(customer_id) as churn_percent 
from mart_customer_churn;  """

  return sql_query

execute_query(query_2_2())

@st.fragment
def cell_2_2():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      with st.container(height=80, border=False, vertical_alignment="center"):
        st.markdown("### Churn Rate")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_2_2", help="Refresh churn_rate data"
      ):
        execute_query.clear(query_2_2())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_2_2())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Calculate metric for scorecard
      if len(df) > 0:
        value = df["CHURN_PERCENT"].sum()
        st.metric(
          label="CHURN_PERCENT",
          value=f"{value:,.0f}"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

# Row 2: 2 Cells
col2_1, col2_2 = st.columns(2)
with col2_1:
  cell_2_1()
with col2_2:
  cell_2_2()

def query_3_1() -> str:
  sql_query = r"""
SELECT market, SUM(total_sales) AS total_sales
FROM mart_daily_sales_by_region
GROUP BY market;  """

  return sql_query

execute_query(query_3_1())

@st.fragment
def cell_3_1():
  with st.container(border=True):
    with st.container(horizontal=True, horizontal_alignment="distribute", vertical_alignment="center"):
      with st.container(height=80, border=False, vertical_alignment="center"):
        st.markdown("### Total Sales by Region")
      if st.button(
        ":material/refresh:", type="tertiary", key=f"refresh_button_cell_3_1", help="Refresh total_sales_by_region data"
      ):
        execute_query.clear(query_3_1())

    try:
      with st.spinner("Executing query", show_time=True):
        df = session.create_async_job(
          execute_query(query_3_1())
        ).result("pandas")

      if any(df.columns.duplicated()):
        new_names = []
        name_indexes = {}
        for name in df.columns:
          name_index = name_indexes.get(name, 0) + 1
          name_indexes[name] = name_index
          new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
        df.columns = new_names

      # Prepare data for bar chart
      if len(df) > 0:
        df = df[["MARKET","TOTAL_SALES"]]

        df["/* Order Key (Generated by Snowflake) */"] = df.drop(columns="MARKET").sum(axis=1)

        datetime_primary_column = None
        if pd.api.types.is_datetime64_dtype(df["MARKET"]):
          datetime_primary_column = df["MARKET"]
        elif df["MARKET"].dtype == "object" and isinstance(df["MARKET"].get(df["MARKET"].first_valid_index()), dt.date):
          datetime_primary_column = pd.to_datetime(df["MARKET"], errors="coerce")
        if datetime_primary_column is not None and (datetime_primary_column.max() - datetime_primary_column.min()).days > len(df) * 2:
          # Use string type for sparse date range
          df["MARKET"] = df["MARKET"].astype("string")

        st.bar_chart(
          df,
          x="MARKET",
          y=[c for c in df.columns if c != "MARKET" and c != "/* Order Key (Generated by Snowflake) */"],
          sort="-/* Order Key (Generated by Snowflake) */",
          width="stretch",
          height=400,
          horizontal=True,
          stack=False,
          x_label="TOTAL_SALES",
          y_label="MARKET"
        )
      else:
        st.warning("No data available")
    except Exception as e:
      st.error(f"Error: {str(e)}")

# Row 3: Single Cell
cell_3_1()


# Footer
st.markdown("---")
st.markdown(
  "*Dashboard loaded: {}*".format(dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
)
