version: 2

models:
  - name: stg_orders
    description: "Staging layer for raw orders data"

    columns:
    - name: order_id
      tests:
        - not_null

    - name: customer_id
      tests:
        - not_null

    - name: product_id
      tests:
        - not_null

  - name: stg_customers
    description: "Staging layer for customers"

    columns:
    - name: customer_id
      tests:
        - not_null

  - name: stg_products
    description: "Staging layer for products"

    columns:
    - name: product_id
      tests:
        - not_null
